import type { RuntimeManifest } from "../types/manifest";
import { buildRuntimeModel } from "./build-runtime-model";

export function buildReactRuntimeFiles(
  manifest: RuntimeManifest
): { entry: string; types: string } {
  const model = buildRuntimeModel(manifest);

  const entry = [
    `/* eslint-disable */`,
    `// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.`,
    `// Generated by @valfuse-node/localization.`,
    `// This file contains runtime localization manifest data used by adapters.`,
    ``,
    `import type { LocalizationManifest, LocalizationNode } from "./localization.types";`,
    ``,
    `const manifest: LocalizationManifest = ${JSON.stringify(manifest, null, 2)} as const;`,
    ``,
    `/**`,
    ` * Type-safe accessor tree — property names preserve source key segments.`,
    ` * Leaf values are full message keys for use with store.t().`,
    ` */`,
    `export const localization = ${JSON.stringify(model.stringsTree, null, 2)} as const satisfies LocalizationNode;`,
    ``,
    `/**`,
    ` * Exact type of the generated localization accessor tree.`,
    ` */`,
    `export type Localization = typeof localization;`,
    ``,
    `export default manifest;`,
    ``,
  ].join("\n");

  const types = [
    `/* eslint-disable */`,
    `// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.`,
    `// Generated by @valfuse-node/localization.`,
    ``,
    `export interface RuntimeManifestEntry {`,
    `  key: string;`,
    `  placeholders: string[];`,
    `}`,
    ``,
    `export interface LocalizationManifest {`,
    `  base_locale: string;`,
    `  fallback_locale: string;`,
    `  locales: string[];`,
    `  entries: RuntimeManifestEntry[];`,
    `  messages: Record<string, Record<string, string>>;`,
    `}`,
    ``,
    `export type LocalizationNode = {`,
    `  readonly [key: string]: string | LocalizationNode;`,
    `};`,
    ``,
  ].join("\n");

  return { entry, types };
}

