/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by @valfuse-node/localization.
// This file contains runtime localization manifest data used by adapters.

import type { LocalizationManifest, LocalizationNode } from "./localization.types";

const manifest: LocalizationManifest = {
  "base_locale": "en",
  "fallback_locale": "en",
  "locales": [
    "en",
    "id"
  ],
  "entries": [
    {
      "key": "common.asset_count",
      "placeholders": []
    },
    {
      "key": "common.runtime_note",
      "placeholders": []
    },
    {
      "key": "common.welcome",
      "placeholders": [
        "name"
      ]
    }
  ],
  "messages": {
    "en": {
      "common.asset_count": "{\"one\":\"{count} asset selected\",\"other\":\"{count} assets selected\",\"zero\":\"No assets selected\"}",
      "common.runtime_note": "This Vue example uses the framework-neutral localization runtime.",
      "common.welcome": "Hello, {name}!"
    },
    "id": {
      "common.asset_count": "{\"one\":\"{count} aset dipilih\",\"other\":\"{count} aset dipilih\",\"zero\":\"Tidak ada aset dipilih\"}",
      "common.runtime_note": "Contoh Vue ini menggunakan localization runtime yang tidak terikat framework.",
      "common.welcome": "Halo, {name}!"
    }
  }
} as const;

/**
 * Type-safe accessor tree — property names preserve source key segments.
 * Leaf values are full message keys for use with store.t().
 */
export const localization = {
  "common": {
    "asset_count": "common.asset_count",
    "runtime_note": "common.runtime_note",
    "welcome": "common.welcome"
  }
} as const satisfies LocalizationNode;

/**
 * Exact type of the generated localization accessor tree.
 */
export type Localization = typeof localization;

export default manifest;
