/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by @valfuse-node/localization.

export interface RuntimeManifestEntry {
  key: string;
  placeholders: string[];
}

export interface LocalizationManifest {
  base_locale: string;
  fallback_locale: string;
  locales: string[];
  entries: RuntimeManifestEntry[];
  messages: Record<string, Record<string, string>>;
}

export type LocalizationNode = {
  readonly [key: string]: string | LocalizationNode;
};
